### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by FastEddyCurrent** [scotthibbs/FDLog_Enhanced#8]
![MemApprox0Min](https://user-images.githubusercontent.com/17724789/60223027-7be4b280-984d-11e9-8c87-ed8f58af4981.jpg)
![MemApprox1Min](https://user-images.githubusercontent.com/17724789/60223029-7dae7600-984d-11e9-8d67-a63309d6c1f1.jpg)
![MemApprox5Min](https://user-images.githubusercontent.com/17724789/60223030-7f783980-984d-11e9-8e78-2c19e9d55a76.jpg)
As you can see the program is leaking memory.
added the pympler and used muppy to track memory
see https://pythonhosted.org/Pympler/muppy.html#
symptom showed lambda functions continuously added with no user activity
function (<lambda>) |       33092 |      1.89 MB
function (<lambda>) |      310148 |     17.75 MB
looked at the code and found the 
update function runs periodically with updatebb().
updatebb() does
                bandb[bm].bind("<Enter>", lambda e: None)
                bandb[bm].bind("<Leave>", lambda e: None)
in 2 places lines 2463-64, 2468-69.
master as of 6/24/2019
These lambdas cause a memory leak because python has to create each anonymous function.
Changed the lambda e: None to just None per John E. Grayson Python and Tkinter Programming book
page 434 
bind(sequence=None, function=None, add=None)
Associates event handlers with events. If add is + the binding is added to the current bindings;
the default is to replace the existing binding.

Please fix.
Thx 
AC8TM

**Comment by nouse4anick** [comment]
I bet thats whats happening to my pi. It froze a couple of times during field day. I'm going to update my fork and see what that does

Thanks!

**Comment by scotthibbs** [comment]
I left my program open on my laptop since field day and it did indeed freeze the computer due to lack of memory. I've merged the changes. I'll leave this issue open, I'll download the new merged changes and test it. 

Big thanks to AC8TM!! We could use more of your help. I barely know any python coding and we got a lot of work for this little gem of a program.

**Comment by nouse4anick** [comment]
so I've been testing it for over a day on my pi and it looks like the memory leak is a lot slower now, top is saying pythons' memory usage is at 13% after a day. if it goes above 15% and I'm not touching it there is another leak in there somewhere. 

I have my laptop's copy on (its the previous one with the bug still in it) to see if some network traffic makes it go higher faster.

Also I'm estimating (and this is on the pi) that its growing at a rate of about 2-3% over 12 hours (roughly)

**Comment by nouse4anick** [comment]
so i confirmed this morning that we do have another memory leak, my pi went from 13% last night (9 hours ago) to 17% this morning.

while this isn't really a huge deal for desktop and laptop users I feel that any amount of leakage is bad especially since the program is cross platform compatible and can run on virtually any linux based system (including system on a chip boards like the pi).

I'll go download muppy and see if i can figure out whats going on with the program.

**Comment by nouse4anick** [comment]
FastEddyCurrent can you share the additions you made and where to find those leaks? I'm having issues making any headway with pympler and muppy... i did try the tracker difference function and put a print out of it in the updatebb function and i do see some stuff there.

mainly:
`
types |   # objects |   total size

========================= | =========== | ============

                     dict |           4 |      1.09 KB

           instancemethod |           8 |    640     B

                 instance |           4 |    288     B

                      str |           4 |    254     B

  function (whosonsecond) |           1 |    120     B

   function (whosonfirst) |           1 |    120     B

`
I'll keep playing with it but any help would be appreciated
Art

**Comment by scotthibbs** [comment]
80 Found our remaining memory leak - removed unnecessary root.update() and root.deiconify() 
- Scott Hibbs KD4SIR 03Mar2022
07Jul2022 Beta 2.0
